### PR TITLE
Create Encode Address in Python3 for Bounty DGE-93

### PR DESCRIPTION
**Pull request by kasiimh1**

### CODE REVIEW

**Comment by kasiimh1** [comment]
Ripple internal ID: DGE-93

Milestone 1

**Comment by wojake** [comment]
Code samples are best written linearly, nested functions are hard to keep up with for code samples.

**Comment by JST5000** [comment]
Here's the updated link to the bounty this PR is referring to: https://github.com/XRPLBounties/Proposals/blob/main/bounties/0032%20Python%20Code%20Samples.md

**Comment by JST5000** [comment]
@kasiimh1 Hey, I'm closing this PR since equivalent work has already been merged, **BUT** we are accepting this work for the Milestone 1 bounty in addition to the work by @wojake on [this PR](https://github.com/XRPLF/xrpl-dev-portal/pull/1490). 

@kasiimh1 please [follow the instructions here to claim this as a bounty](https://github.com/XRPLBounties/Proposals#claim-a-bounty) :) 

(For context on this - the goal of the bounty program is to encourage more people to start developing on important work in the ecosystem, and since this is original work submitted at a similar time with similar quality to the merged code we want to recognize that) 

As an aside: Would you want feedback on your PR even though it's being closed just for learning sake? (If so I'm happy to share comments - but if not that's ok too)

**Pull request closed without merging**
