### PR TITLE
adds  xls-30 banner

### PR DESCRIPTION
**Pull request by AKCodez**

### CODE REVIEW

**Review by intelliot — CHANGES_REQUESTED** [review]
do not merge yet - hold for XRPLF review

**Review by Silkjaer — CHANGES_REQUESTED** [review]
Shouldn't be merged. Voting is irrelevant for 99.9% of visitors and for those that it's relevant will already know. We also shouldn't promote any amendments over others, neither pressure/push validators to vote in favor of anything not fixes.

**Comment by jscottbranson** [comment]
Hello,
Let's not merge this, as it sets a unique precedent given that the vast majority of other amendments have not received a banner when they were available to voting.

**Comment by mDuo13** [comment]
Agreed, the banner should not be used to push for votes on specific amendments.

**Pull request closed without merging**
