### PR TITLE
[DOC] update ripple-rest api changes

### PR DESCRIPTION
**Pull request by geertweening**

### CODE REVIEW

**Comment by geertweening** [comment]
@mDuo13 changes to the ripple-rest API

one of the changes that might affect terminology through the some other parts of the document is the `account/new` to `wallet/new` change. I'll leave it up to you if we want to use the "wallet" through the explanation for the results of that endpoint as well.

**Comment by mDuo13** [comment]
Not sure why we went back to "wallet" (a sort of confusing and overloaded term) when until now REST was blissfully lacking in that terminology -- also, you appear to have some accidental " marks in your edits?

**Comment by geertweening** [comment]
Yeah, I'll take " marks out, my bad.

We went back to `wallet` since you're not really creating an account. You're generating an address and a key and it's not in the ledger yet. Looking up anything using the just generated "account" wouldn't do anything. To separate what an account meant and what this 'new' endpoint meant I was looking for a different term. We settled on "wallet". 

Other suggestions would be great as well, but I would like to keep it separate from "account"

**Comment by mDuo13** [comment]
Maybe "address", then? That's actually closer to what you're generating.

**Comment by geertweening** [comment]
It's an address and a secret. I was looking for something that captures both.

**Pull request merged**
