### PR TITLE
Remove references to amm-devnet

### PR DESCRIPTION
**Pull request by oeggert**
AMM-Devnet is being decommissioned on 12/8.

### CODE REVIEW

**Comment by mDuo13** [comment]
I think you want to rebase on the latest master, dropping everything except [dcc65b7](https://github.com/XRPLF/xrpl-dev-portal/pull/2288/commits/dcc65b7234c9ee6bff7b1b0598cfbe7cad27cc2a).

(The broken links are coming from the PHP PR; fixed in https://github.com/XRPLF/xrpl-dev-portal/commit/e9d17c9a02c2e6de4073742016c7d110aeb8373e so should resolve automatically if you rebase.)

**Comment by ckniffen** [comment]
References on the faucet page also need to be removed.

**Comment by oeggert** [comment]
> References on the faucet page also need to be removed.

This faucets page is built off the jinja file in this PR, so we're good to go.

**Review by ckniffen — APPROVED** [review]

**Review by mDuo13 — APPROVED** [review]
Rebased to remove the extra commits/files, removed AMM-Devnet from the WS tool, and public networks page (EN+JA). While I was there, I updated the Hooks-Testnet to Xahau Testnet to match https://github.com/XRPLF/xrpl-dev-portal/pull/2282

**Pull request merged**
