### PR TITLE
Add `Coin Space` Wallet

### PR DESCRIPTION
**Pull request by mahnunchik**
This PR adds `Coin Space` wallet to list of Software Wallets.

Notes:

1. Styles are not compiled `yarn run build-css` because it produces a lot of not related changes.
2. String translations are not updated `pybabel extract -F ./locale/babel.cfg -o ./locale/messages.pot ./` because there are a lot of not related changes changes.

### CODE REVIEW

**Comment by mahnunchik** [comment]
Could I ask for the review? @mDuo13 @oeggert

**Comment by intelliot** [comment]
I don't see XRP mentioned on the https://coin.space/ homepage (even though other digital assets are there). Maybe it supports XRP but it is not clear/obvious... and of course I have no personal knowledge or experience of Coin Space.

**Comment by mahnunchik** [comment]
@intelliot could you please check it again, this is step by step guide:

1. Make sure your internet connection is turned on
2. Open the website https://coin.space/
3. Navigate to menu item named `Wallet`
4. Open the link https://coin.space/xrp-wallet/

Or you can visit `Features` page https://coin.space/features/

xrp

**Review by Silkjaer — APPROVED** [review]

**Comment by amarantha-k** [comment]
Thank you for your contribution, @mahnunchik!  
Also, for your reference, the underlying toolchain is being migrated to Redocly. I've cherry-picked your changes to be included in the migrated site (PR #2372).

**Pull request merged**
