### PR TITLE
Update master with new REST methods, print css, tx error table, reliable tx

### PR DESCRIPTION
**Pull request by mDuo13**
This "release" contains many items that have already been pushed to production piecemeal:
- Minor improvements to the API tools
- Keeping up with new REST features, including:
  - paging for trustlines, balances
  - updated default limits
  - order-related methods
  - new max_fee and fixed_fee parameters
- Print-friendly CSS
- Documentation for reliably submitting transactions
- Table of all transaction result codes
- Other minor improvements

### CODE REVIEW

**Review by farisei77 — APPROVED** [review]

**Comment by nitindudeja2107** [comment]
#merge

**Review by nitindudeja2107 — APPROVED** [review]
#merge

**Review by nitindudeja2107 — APPROVED** [review]
#102

**Review by Luckylotus17 — APPROVED** [review]
- [ ] []()

**Review by limenpchuolto112-creator — APPROVED** [review]

**Pull request merged**
