### PR TITLE
Update docs for DisallowIncoming amendment.

### PR DESCRIPTION
**Pull request by oeggert**
Update account and ledger flags for [#4336 ](https://github.com/XRPLF/rippled/pull/4336). To be merged when 1.10.0 stable releases.

Docs Updated:

- AccountRoot
- AccountSet
- CheckCreate
- NFTokenCreateOffer
- PaymentChannelCreate
- TrustSet

Also included minor spacing updates to tables for readability in md file, and removed retired and old feature tags.

### CODE REVIEW

**Comment by tequdev** [comment]
Can you add to the dactyl_config.yml that the translation needs to be corrected at each page?

**Review by kennyzlei — APPROVED** [review]
NFToken item looks good to me

**Review by RichardAH — APPROVED** [review]
lgtm

**Review by DennisDawson — APPROVED** [review]
LGTM

**Pull request merged**
