### PR TITLE
feat: Osano for cookie management

### PR DESCRIPTION
**Pull request by justinr1234**

### CODE REVIEW

**Comment by mDuo13** [comment]
Maybe should wait for the updated privacy policy before merging this?

**Comment by justinr1234** [comment]
> Maybe should wait for the updated privacy policy before merging this?

I think it can go without as it’s turned off in the backend.

**Review by intelliot — APPROVED** [review]
I guess this is called Osano (not Osana as the PR title currently says)

**Comment by justinr1234** [comment]
> I guess this is called Osano (not Osana as the PR title currently says)

Fixed, thanks for catching!

**Pull request merged**
