### PR TITLE
Tip to change permissions on rippled.cfg

### PR DESCRIPTION
**Pull request by alloynetworks**
Make the rippled.cfg file readable only by the rippled user and root, with 0600

### CODE REVIEW

**Comment by mDuo13** [comment]
Should probably mention that you want to do this as the `rippled` user. 

In general it feels kind of incomplete just add a mention about user permissions without actually clarifying the recommended model.

**Comment by alloynetworks** [comment]
You cannot do it as the user rippled. That user doesn't have a $HOME or a `passwd` entry, so I don't quite understand what you're getting at.

**Comment by alloynetworks** [comment]
Well you can su to that user from root, but that will land you in / . The packaging creates the files and directories in /opt/ripple as `rippled:rippled` so doing a chmod will leave it as that user.

**Comment by mellery451** [comment]
@mDuo13 I don't think `chmod` cares who the invoking user is except that it must either owner or root to change perms - so this is just setting the mask to be strictly owner read/write. root seems like the right way to do that. The owner should remain `rippled` and we're not suggesting changing that.

**Comment by mDuo13** [comment]
Yeah, I was thinking about cases other than the supported install, but I was mixed up on how chmod would work. Now that I understand better, I realize you're right that this is a good suggestion regardless.

I still think it would be a good doc to add to describe the recommended permissions setup as implemented by the supported packages. That would make it easier to build a similar setup on non-supported distros.

**Pull request merged**
