### PR TITLE
Closes #639

### LINKED ISSUE #639: Start BUIDLing
Correct spelling and capitalization of Building in the "Start Building" section. 

image

### PR DESCRIPTION
**Pull request by iroskam**
Typo "BUIDLing" in Start Building section header.

Corrected spelling and capitalization to Building.

### CODE REVIEW

**Comment by mDuo13** [comment]
That's not a typo, it's a joke, or kind of a meme, like "HODL" but more constructive.

The best explanation I've seen is [this article](https://mashable.com/article/buidl-hodl/).

**Comment by iroskam** [comment]
I suspected it was a reference to the HODL meme.  I don't think that documentation is a place for drunken typo meme joke references.  To readers that are not familiar with the meme it just looks unprofessional.

**Comment by intelliot** [comment]
Not sure if we're taking votes, but FWIW I would be fine with changing this to `Building`

**Comment by mDuo13** [comment]
Personally, I like the playful style, but I get where you're coming from. I guess it's fine to change.

**Pull request merged**
