### PR TITLE
Update unfreeze_token.py

### PR DESCRIPTION
**Pull request by ObiajuluM**
minimal changes

### CODE REVIEW

**Comment by mDuo13** [comment]
Why? Per [the tutorial step for this](https://xrpl.org/freeze-a-trust-line.html#7-optional-send-trustset-transaction-to-end-the-freeze):

> The amount of currency you trust this counterparty to issue to you, as a quoted number. As an issuer, this is typically "0".

**Comment by ObiajuluM** [comment]
Ahh, I see. But doesn't this mean that I'll have to set the value parameter in freeze token to '0'? [here](https://xrpl.org/freeze-a-trust-line.html#4-send-trustset-transaction-to-freeze-the-trust-line) 
Screenshot_20221207-035524

**Comment by mDuo13** [comment]
Yes, that's a good point.

**Comment by ObiajuluM** [comment]
If I set the value in either the freeze or the freeze transactions to '0', it will require the other party to reset the trustline to its previous value. It will be stressful.

**Comment by mDuo13** [comment]
I think the core issue is better addressed in a separate, more comprehensive PR. Closing this one since it's stale.

**Pull request closed without merging**
