### PR TITLE
ambassador page button and typeform updates

### PR DESCRIPTION
**Pull request by AKCodez**

### CODE REVIEW

**Comment by AKCodez** [comment]
Link to ASANA ticket - https://app.asana.com/0/1202192098244985/1203911520144047

**Comment by AKCodez** [comment]
Link to ASANA ticket - https://app.asana.com/0/1202192098244985/1203423750481586

**Review by jonathanlei — APPROVED** [review]

**Comment by jonathanlei** [comment]
"/deploy-preview"

**Pull request merged**
