### PR TITLE
Correct tfSetAuth typo

### PR DESCRIPTION
**Pull request by RareData**

### CODE REVIEW

**Comment by mDuo13** [comment]
Thanks for the contribution, but that's [not a typo](https://github.com/ripple/rippled/blob/381a1b948b06d9526cc73f14cfc69635fabf8605/src/ripple/protocol/TxFlags.h#L89).

I don't know why the flag is "Set F Auth" but it is.

**Comment by RareData** [comment]
This says otherwise: https://github.com/ripple/xrpl-dev-portal/blob/master/content/references/rippled-api/ledger-data-formats/ledger-object-types/ripplestate.md#ripplestate-flags

**Comment by RareData** [comment]
What's up with this? https://github.com/ripple/rippled/blob/develop/src/test/app/SetTrust_test.cpp#L151

**Comment by mDuo13** [comment]
The RippleState doc has a typo.

That other line of code you linked is correctly using `tfSetfAuth` but the comment above it has the typo.

**Pull request closed without merging**
