### PR TITLE
TOML Add x in the principal's details

### PR DESCRIPTION
**Pull request by ihomp**
X handle of the principal, where one can express opinion about voting for amendments and post validator restarts.

### CODE REVIEW

**Comment by Silkjaer** [comment]
I think it's best to keep it vendor neutral, but maybe instead of naming X add a line for alternative way of connecting (which could then be X/Telegram/LinkedIn or whatever preferred)?

**Comment by jscottbranson** [comment]
Currently, the TOML spec clarifies that the file can contain any properly formatted custom field.

I wonder about people having the option of using a social media domain (e.g., LinkedIn.com = "username") as a key and their username as a value, to avoid any vendor lock in.

Alternately, it could be a list of social media URLs, maybe like:

social_1 = "https://website.tld/username"

social_2 = "..."

The benefit of option 2 is that it can provide an ordered list.

I think it's nice to have extra contact info, particularly for getting updates about the server, however, I also feel it's important to avoid pressuring anyone into using a particular platform.

**Comment by ihomp** [comment]
I don't see a pressure here to use a particular platform. 
It's just an example, of how to format data, the example can be extended. 

```
x = "username"
linkedin = "username"
telegram = "username"
wechat = "username" 
kakaotalk = "username"
...platform = "username" 
```

right now some have
`twitter = "@username"`
or 
`twitter = "https://twitter.com/username"`

it would be good to have an example for a format to follow.

**Comment by jscottbranson** [comment]
I definitely see the value in having a consistent spec. Would you be ok editing the original PR to reflect this being across platforms?

**Comment by ihomp** [comment]
@jscottbranson how do I reflect that? - 1) by adding more examples  in the list. or 2) by adding a note that it's not limited to "X" only. Or 3) both

**Comment by jscottbranson** [comment]
Personally, I would find option 3 helpful :+1: .

In addition to another example or two, I think I would benefit from having clarity about how to extend the social media list. For example, highlighting that just the platform name should be used, instead of the domain:

`The X username/handle where this principal can be contacted. For consistency, use site names, not domains, when specifying social media platforms.`

**Comment by amarantha-k** [comment]
In preparation for the toolchain migration to Redocly, the proposed changes have been ported to the `redocly-migration` in #2377.

**Pull request closed without merging**
