### PR TITLE
Add fields to NFTokenMint

### PR DESCRIPTION
**Pull request by DennisDawson**
Per https://ripplelabs.atlassian.net/browse/DEFI-154.

### CODE REVIEW

**Review by tequdev — CHANGES_REQUESTED** [review]
It would be better to mention that it is only available after activate the NFTokenMintOffer Amendment.

And could you also add to the Japanese page?
I don't mind if it remain in English.

**Comment by DennisDawson** [comment]
Converting this to draft - this will not be pulled until the feature is live on Mainnet.

**Comment by DennisDawson** [comment]
Per tequdev request, copied the English version into the Japanese internationalization directory.

**Comment by tequdev** [comment]
It was intended to add only three fields in English to the end of the table.

**Review by tequdev — DISMISSED** [review]

**Review by Topher68chris — APPROVED** [review]

**Comment by Topher68chris** [comment]
Got you

**Review by amarantha-k — APPROVED** [review]
LGTM

**Pull request merged**
