### PR TITLE
chore: remove top exchanges

### PR DESCRIPTION
**Pull request by justinr1234**

### CODE REVIEW

**Review by ckniffen — APPROVED** [review]

**Comment by Silkjaer** [comment]
It's not sufficient to remove FTX – Liquid has also halted trading. So I suggest either updating the list to actually reflect CryptoCompare, as it says, or remove the "top exchanges" altogether. I personally think it's better to remove them :)

**Comment by justinr1234** [comment]
> It's not sufficient to remove FTX – Liquid has also halted trading. So I suggest either updating the list to actually reflect CryptoCompare, as it says, or remove the "top exchanges" altogether. I personally think it's better to remove them :)

Do you know where the link is? I couldn’t find where this original list came from.

**Review by intelliot — APPROVED** [review]
This is in a section called "Top Exchanges, according to CryptoCompare". In general, the CryptoCompare list has changed significantly, and the list here has not followed it. Consider removing the list from this page entirely, and perhaps linking to some external resource instead.

**Comment by intelliot** [comment]
FWIW, I do not know where the original list is from.

**Comment by Silkjaer** [comment]
Agreed. I think CryptoCompare introduced other measures to rank exchanges as well, so removing it is fine.

**Comment by justinr1234** [comment]
@Silkjaer @intelliot I added a link to coinmarketcap which has a nice list it seems. Please let me know what you think.

image

**Comment by Silkjaer** [comment]
I still think it's better to just remove it. If not, it should be rephrased (it's not XRPL exchanges, and you may not want to only obtain XRP) 👍🏻

**Comment by justinr1234** [comment]
@Silkjaer Updated, let me know

**Pull request merged**
