### PR TITLE
Mark Flow as enabled and remove FlowV2

### PR DESCRIPTION
**Pull request by wilsonianb**

### CODE REVIEW

**Comment by mDuo13** [comment]
I'd like to leave mention of the Flow V2 amendment for reference.

**Comment by wilsonianb** [comment]
So just leave this?
`This Amendment supersedes the FlowV2 amendment.`

**Comment by mDuo13** [comment]
and also leave the FlowV2 entry in the table that notes it was vetoed/removed

**Comment by wilsonianb** [comment]
Now only the FlowV2 section has been removed. Content previously linking to it now links to the FlowV2 veto blog post.

**Comment by mDuo13** [comment]
build failure is benign (websocket.org is down right now)

**Pull request merged**
