### PR TITLE
Remove outdated build instructions

### PR DESCRIPTION
**Pull request by thejohnfreeman**
Addresses #1651. The first commit in this PR removes all build instructions, indiscriminately, without adding any links to the build instructions in the rippled project. It was suggested that I submit this anyway to start the discussion.

### CODE REVIEW

**Comment by intelliot** [comment]
These instructions are obsolete; it won't hurt anyone to remove them. They'll always be available in the commit history, regardless (in addition to archive.org presumably).

**Comment by mDuo13** [comment]
These instructions are still accurate for building the latest stable release (1.9.4) from source, aren't they? I'm hesitant to replace the build instructions completely until we have a stable release based on Conan.

Also, you need to update `dactyl-config.yml`, or the build will fail (as it currently is) due to missing files. We prefer to leave redirects in place rather than taking URLs down entirely.

**Comment by oeggert** [comment]
I agree that we should hold off on deleting the pages from xrplf if the instructions are valid. I can help update BUILD.md from the linked issue and then set up redirects to it once that goes out with a stable release.

**Comment by oeggert** [comment]
Closing this PR. I've got another open that removes the old instructions and adds redirects. #1789

**Pull request closed without merging**
