### PR TITLE
Data Types: issued currency→token

### PR DESCRIPTION
**Pull request by mDuo13**
Updates a couple mentions of the words "issued currency" that didn't get changed in #1344.

### CODE REVIEW

**Comment by wojake** [comment]
Are we going to call them IOUs, issued currencies, or tokens? They're all the same, I don't get why we're calling them using different terms.

**Review by amarantha-k — APPROVED** [review]
lgtm

**Review by amarantha-k — COMMENTED** [review]
Link checker shows broken links; PTAL and resolve before merging.

**Comment by mDuo13** [comment]
> Are we going to call them IOUs, issued currencies, or tokens? They're all the same, I don't get why we're calling them using different terms.

We are calling them "Tokens". The point of this PR is to move away from some of the previous usage.

**Pull request merged**
