### PR TITLE
changes learn more link and text for nft pencil banner

### PR DESCRIPTION
**Pull request by AKCodez**

### CODE REVIEW

**Comment by AKCodez** [comment]
Link to ASANA ticket - https://app.asana.com/0/1202192098244985/1203859918247357

**Comment by DennisDawson** [comment]
Not certain whether the build failure is caused by the proposed changes.

> Error: Unable to process file command 'env' successfully.
> Error: Invalid value. Matching delimiter not found 'EOF'

**Comment by AKCodez** [comment]
Did a bad conflict resolution, fixing testing and pushing

**Comment by AKCodez** [comment]
Can't seem to figure out what is causing the failed build.

**Comment by AKCodez** [comment]
Going to make a new PR

**Comment by AKCodez** [comment]
Link to new PR @DennisDawson https://github.com/XRPLF/xrpl-dev-portal/pull/1738

**Pull request closed without merging**
