### PR TITLE
Add example of Ledger Close Time determination

### PR DESCRIPTION
**Pull request by movitto**
Expands upon documentation providing example of how Ledger Close Time determination works

### CODE REVIEW

**Comment by thejohnfreeman** [comment]
Yes, that is how it works. Here is the code that adjusts the close time:

https://github.com/ripple/rippled/blob/8a25f3282426f382e1933242ef875d5aaf3e31e9/src/ripple/app/consensus/RCLConsensus.cpp#L465-L478

The first branch is when the close time is effectively "zero" signaling there was no consensus close time. In that case, it uses the previous close time plus one second, as you write.

The second branch adjusts when the close time is agreed in consensus. That calls this function:

https://github.com/ripple/rippled/blob/8a25f3282426f382e1933242ef875d5aaf3e31e9/src/ripple/consensus/LedgerTiming.h#L152-L165

Ignore the early return. It returns the maximum of a rounded close time and the previous close time plus one second. The rounding looks like this:

https://github.com/ripple/rippled/blob/8a25f3282426f382e1933242ef875d5aaf3e31e9/src/ripple/consensus/LedgerTiming.h#L129-L139

If the `closeResolution` is 10 seconds, then this effectively rounds to the nearest 10th second.

**Review by thejohnfreeman — APPROVED** [review]

**Comment by mDuo13** [comment]
Per @nbougalis:

> The steps are a little mixed up:
> 1) Validators individually determines the proposed close time and include that time in their proposals. Let's assume 2 validators are proposing a close time of 12:00:03, and one is proposing a close time of 12:00:04.
> 2) Validators examine other's proposals to determine the consensus time. In this case, the resulting consensus time is 12:00:03.
> --- Voting process over. Everything else is deterministic. ---
> 3) The validators first "round down" this value to the nearest "interval" (a value also negotiated by consensus, currently 10 seconds) resulting a consensus time of 12:00:00. But since this value is identical to the previous ledger's close time, validators deterministically execute code that "adjusts" the close time to be precisely 1 second greater than the last ledger's close time.
> 4) The "adjusted" consensus time is 12:00:01.

Which in is the opposite order of how I thought it worked, but makes sense.

**Comment by thejohnfreeman** [comment]
I don't think I would characterize it as "round down". It's a "round", the typical rounding where if it meets or crosses the half-interval it rounds up to the next interval. Right?

**Review by intelliot — APPROVED** [review]

**Review by wojake — APPROVED** [review]

**Comment by mDuo13** [comment]
> I don't think I would characterize it as "round down". It's a "round", the typical rounding where if it meets or crosses the half-interval it rounds up to the next interval. Right?

Based on [this line of code](https://github.com/ripple/rippled/blob/8a25f3282426f382e1933242ef875d5aaf3e31e9/src/ripple/consensus/LedgerTiming.h#L138), I think it is actually a "round down" or "floor" operation using the mod (`%`) operator:

```
return closeTime - (closeTime.time_since_epoch() % closeResolution);
```

But I may be reading that wrong. The comment seems to suggest it rounds up too.

**Comment by thejohnfreeman** [comment]
You have to take [these two lines](https://github.com/ripple/rippled/blob/8a25f3282426f382e1933242ef875d5aaf3e31e9/src/ripple/consensus/LedgerTiming.h#L137-L138) together, which is a conventional round. Rounding numbers in the half-open range [10.5, 11.5) to 11 is like adding 0.5 and flooring.

**Pull request merged**
