### PR TITLE
Migrate Toolchain to Redocly

### LINKED ISSUE #2131: Migrate toolchain used to publish xrpl.org from Dactyl to Redocly
By moving to a sustainable and viable toolchain, we can mitigate/avoid the risk of a single point of failure for the maintenance and future development of the toolchain used to publish xrpl.org.
The Redocly Developer Portal supports the docs-as-code workflow and offers a CI/CD service. 
- Contributors can continue to author in Markdown. Redocly supports Markdoc too.
- The contribution workflow remains the same - contributors open a PR for review and PRs require all checks to pass and at least 1 approval before they can be merged.  
- Commits merged to the production branch will be published to the site automatically; this will be a huge improvement from the current situation where updates need to be published manually.
- Similar to the current experience, members of the XRPL.org Editors team will have access to the Redocly portal for admin tasks.

### PR DESCRIPTION
**Pull request by mDuo13**
Migrates the XRPL Dev Portal repository off Ripple's in-house toolchain, Dactyl, to the new Redocly "Realm" portal. Fixes #2131.

This branch probably does not need to be rebased on the `master` branch any more times.

Known issues / TODOs:

- [x] Fixed various CSS issues. In many cases, the CSS was in place already, and just needed to be slightly modified due to different class hierarchy on the new site.
    - [x] Fixed issues with theme-aware diagrams, so they should all be visible enough in both light and dark modes again
    - [x] `monospace` table elements are no longer cut off too aggressively.
    - [x] top nav styling fixed
    - nesting in left nav is less visible than we'd like (Non-blocker, tracked in https://github.com/XRPLF/xrpl-dev-portal/issues/2350)
    - [x] badges no longer display as block items
    - [x] Linking to a header (by anchor) doesn't push it under the top nav anymore, but the invisible header spacers shouldn't block (much) directly above them.
    - [x] Tutorials page cards now display correctly
    - [x] Fixed missing graphics on Docs homepage
- [x] Fixed all broken links reported by Redocly, including:
    - [x] `_template-admin-method.md` now properly ignored (fixed after updating Realm bug to 0.74.1 and modifying the ignore stanza)
    - [x] Fixed relative paths for Japanese-translated pages linking to untranslated pages
    - [x] Removed links to pages that no longer exist
    - [x] Updated the migration script to define reusable "common" links using `{% raw-partial ... /%}` and use it anywhere the old common links snippets were being used. The new common links file, `content/_snippets/common-links.md`, is in alphabetical order.
    - [x] Fixed un-migrated reference links in Japanese like `[account_infoメソッド][]` appearing in the output, including issues with case-sensitive replacement (by using the common links file)
    - [x] Reference links in the form `[link text][link definition]` work correctly again, assuming the link definition is valid (including part of the common links)
    - [x] Fixed common-links paths not being migrated correctly
    - [x] Fixed issues with unparsed reference-style that rely on common-link definitions but are used in snippets. These snippets should be included as `{% raw-partial ... /%}` instead of `{% partial ... /%}`
    - [x] Fixed links on the Tutorials page. (Paths in `{% xrpl-card href="..." /%}` need to use the web path, which doesn't include the trailing `.md`)
    - [x] Fixed broken links on docs homepage
- [x] Migrated dev blog from Ripple's private https://github.com/ripple/dev-blog/ repo.
    - Landing pages for categories/labels are not migrated, though. (Non-blocker, tracked in #2350)
- [x] Interactive tutorials don't work properly if you navigate to them from another page (caused by an unresolved Realm bug as of 0.75.0)
- [x] Problems with the "Issue a Fungible Token" page (fixed with updates and Realm 0.75.0):
    - [x] Generate Credentials step no longer errors out due to missing locale info
    - [x] Fixed issues with regular expressions in `pattern=` attribute (after a browser update changed the behavior of this field, certain characters need to be escaped that didn't need to be escaped before)
    - [x] The Configure Issuer step doesn't unlock correctly. (Fixed in 0.75.0 - #2387 )
    - [x] Checkboxes in interactive sections are no longer treated as read-only. (Caused by a Redocly bug, fixed in 0.74.4)
- [x] "Re-levelization": Moved non-docs contents to the top level, and renamed  `content/` so that documentation (and docs URLs) are under `docs/`. This involved temporarily breaking, then fixing, a lot of paths including redirects, links into/out of docs, image paths, etc.
    - [x]  Fix the 404 for `favicon.ico`.
- [x] Updated many tutorials' file & URL paths to match their place in the side navigation.
- [x] Marketing pages have had the sidebar turned (back) off
- [x] Fixed all duplicate key errors in custom pages
- [x] Top nav needs some adjustments / updates, especially the Docs dropdown. (Some of the problems will be resolved with CSS fixes.)
- [x] Migrated site footer
- Localization for some pages, particularly dev tools, needs more attention/work. (Some strings that should be translated aren't, or are split up in ways that aren't appropriate.) (Non-blocker, tracked in #2350)
- [x] #2330
- [x] Redirects from old `/*.html` filenames to the new URLs, with the exceptions of the following, which don't have pages in the new site currently:
    - [x] `docs-index.html` - Redirected to `/docs/` for now. Still need to investigate re-creating under Redocly
    - [x] `tutorials.html`
    - [x] `nfts-using-python.html`
    - [x] `php.html`
    - [x] `get-started.html` - removed page. Redirect to the tutorials page (broken link until that one has been migrated). Still need to find and remove old links to this page.
    - [x] `production-readiness.html` - removed page. Redirect to the tutorials page (broken link until that one has been migrated). Still need to find and remove old links to this page.
    - [x] `references.html`
    - `404.html` - no need to redirect this.
    - `sitemap.txt` - Need to figure out where Redocly publishes its sitemap (Non-blocker, tracked in #2350). Being addressed in PR #2393 
    - [x] `robots.txt` - Put it in `/static/` so Redocly serves the existing file.
    - [x] Fixed issue with landing pages being incorrectly redirected to a path ending in `/index`, e.g. `concepts/index.md` now correctly goes to `concepts/` not `concepts/index`.
- Contributor documentation hasn't been entirely updated for the new toolchain. (Non-blocker)
- XRPL-AI chatbot (Beta) needs to be added in Redocly (Non-blocker, tracked in #2350)
- [x] Migrated `:not_enabled:` syntax to a Markdoc component (`{% not-enabled %}`)
- [x] Migrated badge link syntax. The new syntax attempts to automatically provide the preferred color based on the first half of the label such as `New in:` or `Open for Voting:`.
- [x] "Full Docs Index" page isn't migrated - redirected instead for now (Non-blocker, tracked by https://github.com/XRPLF/xrpl-dev-portal/issues/2350)
- [x] Tutorials page migrated
- [x] References page migrated
- [x] Pages that use the `{% repo-link %}` component are broken on preview build but work on local dev server. Seems related to environment variables. These pages show the error: `Cannot read properties of undefined (reading '-1')` (Reported to Redocly) Broken pages include Get Started Using PHP, Cryptographic Keys, Binary Format, Commandline Usage, Build a Browser Wallet in Javascript. Reported Redocly bug and fixed in v0.74.5. 
- [x] Hid `{.github-code-download}` syntax for now. Previously we used that to apply a class that could help to track downloads, but that doesn't work for now.
- Known issues with anchor links:
    - [x] Linked pages sometimes weren't scrolled to the right place (Redocly bug reported, fixed in v0.74.3)
    - [x] "In this page" / page table of contents links containing Japanese text work now (Redocly bug fixed v0.74.4)
    - Links with anchors in Japanese-translated pages don't work as expected if link-substitution was applying to those before. (Non-blocker, tracked in #2350)
- [x] Back button now works correctly after refreshing a page (Redocly bug reported & fixed in v0.74.3)
- [x] Code samples page works again. The root cause was that `content/@theme/plugins/code-samples.js` had a section (a call to `addRouteSharedData(...)`) that needed to be updated with the new path to the code samples page when it was moved.
- Local dev server runs slowly due to markdoc validation step after implementing the `common-links.md` file. (Reported to Redocly, significant improvements in v0.74.3, with further improvements expected in future releases, though some may take a while since the root cause is in a dependency of a dependency.)
- [x] Deprecated pages like Data API are no longer listed in the sidebar, and they have had their metadata updated so that they show the sidebar anyway (using Realm's ["Set sidebar" feature](https://beta-docs.redocly.com/author/how-to/configure-nav/sidebar/#set-sidebar))
- [x] Fixed missing image in Stablecoin Settings page
- [x] On mobile, the top nav should close when you use it to navigate to a new page. Fixed by #2376.

### CODE REVIEW

**Comment by mDuo13** [comment]
Note: the merge conflicts are from #2364. To resolve, delete the files / leave them deleted. @AKCodez will open a separate PR to make the equivalent changes on Redocly.

**Comment by AKCodez** [comment]
[PR](https://github.com/XRPLF/xrpl-dev-portal/pull/2376) to fix final checkbox of "On mobile, the top nav should close when you use it to navigate to a new page" .

**Comment by tequdev** [comment]
Will the Japanese version of some side menus and content itself, which are still in English, need to be translated again in the future? Can we use existing translated content?

**Review by justinr1234 — COMMENTED** [review]
- The homepage image container div ideally needs dimensions set as it causes a large layout shift (affecting core web vitals)
- issue with line at bottom on mobile
IMG_7269
- when you expand a menu item on mobile, a flash of the background bleeds through https://www.loom.com/share/29d9ba62e78d4540a93a09ed645fa319
- Search bar icon color is not accessible / hard to see in light mode
IMG_7270
- clicking into search mode on mobile has no way to close out
IMG_7271
- the page scrolls behind the open menu on mobile. If you scroll and then try to tap a menu item, it takes 2 taps.
- Clicking a menu item on mobile often results in a delay on page change depending on network connection speed, even though the menu changes (this means the react code isn’t handling transitions properly in spa mode)

**Review by tequdev — COMMENTED** [review]
Cannot change language on mobile.

Also, a certain number of Japanese pages, including the top page, remain in English.
Since many of the pages have already been translated, if you could migrate the Japanese pages as well, that would be very helpful.

And please let us know how this would change the workflow for translators. (documentation-translations.html?).

**Comment by amarantha-k** [comment]
@tequdev Yes, we plan to migrate the already translated pages and will create a separate PR for that. (Task tracked in #2350) We'll need your help to review and fix/update the translated pages in cases where significant portions of the English versions have been revised/updated. 

And good idea to add a separate page describing the workflow for translations under Contribution Guidelines. (Tracked by #2394)

**Review by Silkjaer — APPROVED** [review]
All looks good to me, from a quick review. Except the search popover in light mode has a black background. Apart from that , all good.

**Comment by justinr1234** [comment]
@amarantha-k the readme needs to be updated for redocly. Both for contributing as well as an explanation of how the site is configured and how it works overall. For instance, what is `@redocly/realm`?

**Comment by justinr1234** [comment]
@amarantha-k What version of nodejs is this supposed to be targeting? And npm. It would be good to update package.json to include the `engines` field and also a `.nvmrc` would be useful as well as a `.npmrc`

**Comment by amarantha-k** [comment]
@SocketSecurity ignore npm/@cocalc/ansi-to-react@7.0.0
@SocketSecurity ignore npm/core-js-pure@3.35.1

**Pull request merged**
