### PR TITLE
add TypeScript AMM sample code

### PR DESCRIPTION
**Pull request by mashharuki**
Hey!!
I participated in the DeFi Hackathon in Japan in December.

I had a very hard time getting the AMM functionality to work at that time and developed sample code.

This sample code contains code that allows you to try out a full range of AMM-related functions such as DepositAMM, WithdrawAMM, and Swap, in addition to CreateAMM.

I would like to contribute the sample code I created to make it easier for developers to use the AMM feature of XRPL in the future.

Please check it.

[Hackathon Summary]
https://lu.ma/xrpl-hack

[Product created in the hackathon]
https://github.com/mashharuki/DCCEX

### CODE REVIEW

**Comment by mDuo13** [comment]
At a quick glance, the code looks nice! I would like to try running the code, but I don't have much experience with TypeScript. Isn't there typically a `package.json` or similar file to list dependencies? If so, can you add a simple one to this PR?

Also, a note to other reviewers: We don't have an icon for TypeScript yet, so I think our code samples page will report a broken link unless we add one along with this PR and modify `template/page-code-samples.html.jinja` to use it (like https://github.com/XRPLF/xrpl-dev-portal/commit/e9d17c9a02c2e6de4073742016c7d110aeb8373e )

**Comment by mashharuki** [comment]
@mDuo13 Thank you for checking!

Of course!!

`package.json` is here!

https://github.com/mashharuki/DCCEX/tree/main/pkgs/scripts

↑ There are other config files in this folder

**Review by Fuk2828 — APPROVED** [review]

**Comment by tequdev** [comment]
@mashharuki 

It is preferred that `package.json` and `tsconfig.json` be included in `content/_code-samples/create-amm/ts`.
Sample code must be completed in only `content/_code-samples/create-amm/ts`.

**Comment by mashharuki** [comment]
@tequdev ok! I will add package.json & other config files!!

**Comment by mashharuki** [comment]
@mDuo13 @Fuk2828 @tequdev I added `package.json` & `.env.example` & `tsconfig.json` files in this PR! Please check it!

**Comment by mashharuki** [comment]
Thank you everyone!!

**Pull request merged**
